### PR TITLE
DM-29505: prototype Amplifier and AmpliferSet classes

### PR DESCRIPTION
**Pull request by TallJimbo**
Reviewers should start with [doc/lsst.amplifier_images/proposal.rst](https://github.com/lsst-dm/amplifier_images/compare/master...tickets/DM-29505#diff-d41979f4693a19aa2f43aad0f7e71b07a1e5cd8d60fd0a666d80f3707241d5f5), which contains an overview of the proposal.

There was supposed to be a sphinx-generated HTML version of that with convenient links to the docs of all of the classes, but I've spent too much time already trying to get sphinx from infinitely recursing already; commenting on the source directly is probably easier anyway, and the classes are pretty much each in their own file, so hopefully the lack of links isn't too bad.

DM reviewers may be surprised by the ambition of this proposal, but if they look closely I hope they'll agree that it's much bigger in a conceptual sense than in a practical, how-much-code-changes sense (or at least any big practical changes are optional things to consider at the end, not something we need to do up front).

I'm hoping Camera reviewers can focus on whether these classes would address their needs without being distracted too much by the solving-cameraGeom-problems side goals (unless they're interested in that problem, too).

### CODE REVIEW

**Comment by eacharles** [comment]
Thanks for doing this, overall it makes a lot of sense. 

Can you describe a bit more how the we would use this?   Specifically, 1) how we might get an exposure and iterate over amps in a pipeline task and, 2) how we might a run a small part of the Isr as a subtask to perform bias subtraction, defect masking and application of gains to the amplifier data?   It think I know the answer to the first question, but I'd like to be sure.  I'm less clear about the answer to the second questions.

**Comment by TallJimbo** [comment]
> how we might get an exposure and iterate over amps in a pipeline task

If it all goes according to plan, you'd use `raw.amps` in your `PipelineTask` connections rather than `raw`, and in `runQuantum`, you'd read them with something like `parameters={"amps": [n]}` to tell it to load just one (maybe inside a loop).  The same approach would work for master calibrations, at least when reading them; when writing them you'd still be expected to write a full detector.

I wouldn't really expect you to interact much with `Exposure` directly at all in that scheme, except perhaps as the output type when writing those master calibrations.  The butler would give out `AmplifierSet` objects containing `Image` or `MaskedImage` objects, and you'd use those instead.

> how we might a run a small part of the Isr as a subtask to perform bias subtraction, defect masking and application of gains to the amplifier data

This will definitely require some modifications to `IsrTask`, to refactor the `run` method into multiple methods that the `eotest` task can call instead.  Each of those methods would operate either on an `Amplifier` object (one of the new ones from this package) or on a bare `MaskedImage` without caring whether it represents the full detector or a single amp.

The good news is that this is already true in a lot of steps, because `IsrTask` already delegates all of the real work to a subtask that doesn't care what the image it's given represents (as long as it's consistent with the calibration data it's also given).  But there's also still a lot of logic for other operations within `run` itself, and the overscan correction code in particular will need to be modified to work on these `Amplifier` objects instead of assuming it can use `Detector` bounding boxes to extract amplifier subimages from a full-detector image.

We might also want to add some intermediate roll-up methods that both `IsrTask.run` and the `eotest` task could call to help keep the high-level ordering of operations consistent between them.

**Comment by eacharles** [comment]
Ok thanks, this all seems good.  Thanks for doing this so quickly.  
FWIW, from the EO test point of view, the per-amp IsrTask functions (the names are just suggestions) that we are going to need are: 

IsrTask.subtractOverscan(amp : Amplifier) -> Amplifier 
IsrTask.subtractBias(amp : Amplifier, bias : Exposure) -> Amplifier 
IsrTask.maskDefects(amp : Amplifier, defects : Defects) -> Amplifier
IsrTask.applyGain(amp : Amplifier, gain : float) -> Amplifier

And likely something that chains those together. 

We might eventually want:
IsrTask:subtractDark(amp : Amplifier, dark : Exposure ) -> Exposure
IsrTask:linearize(amp : Amplifier, linearizer : Linearizer) -> Exposure

I think in each case it is perfectly reasonable to have the operation work in place.

**Comment by TallJimbo** [comment]
I had a chat with @rhl about this, and he pointed out that it'll work much better to adapt `IsrTask` to handle single amplifiers by making it think it's working on a full single-amplifier detector, rather than a possibly-incomplete set of amplifier images.  I think the only change needed to the prototype code here would be to allow an `AmplifierSet` with exactly one amplifier to be assembled, as well as one with a complete set of amplifiers.

I'm not completely sure where that leaves the classes in this proposal; they'd still be very useful for some aspects of what you need (particularly making the behind-the-butler code capable of reading single amps and providing camera geometry for them), but whether it's also useful to modify `IsrTask` to use these instead of our existing `Exposure`+`cameraGeom` classes is only tangentially related to the `eotest` use case (in that if we use these classes behind the butler, it'd be nice not to have to them convert them into `cameraGeom` classes for `IsrTask`, _if_ there are sufficient other reasons to prefer the new classes in `IsrTask`).

A related question for @czwa is whether we can clearly characterize all fields in `cameraGeom.Amplifier` as either something that should go in these new classes (i.e. because it's exactly knowable and static - or derivable from raws) or something that should go in an `IsrCalib`.  If we can, and those `IsrCalibs` exist or will soon, then I think transitioning `IsrTask` to these new classes may be a net win early, because the changes in `IsrTask` will be good to have done and the work involved in making those changes is at least partially canceled by the simplification of the butler reading code.  If the characterization of `Amplifier` fields is more nebulous, or the full `IsrCalib` transition is further away, then I think we're better off either tabling these classes for now or using them only behind the butler and converting to regular `cameraGeom` objects either at the end of that code or the beginning of `IsrTask`.

**Comment by czwa** [comment]
The majority (it should be all, but I'm hesitant to assert that's true at the moment) of the Isr functions should have multiple "entry point" functions.  When I did the last big refactor, I worked to make all `IsrTask.doSomething` methods operate on an `Exposure`, and then after performing whatever additional bounding box/metadata/etc lookups, pass the `MaskedImage` and appropriate other information to an `isrFunctions.actuallyDoSomething` function.  The logic behind that was to split the pure math (subtracting the overscan, as an example) from the bounding box operations.  Given that, it's entirely possible that the majority of the "eotest isr functions" listed above already exist in `isrFunctions`, and can be given amplifier `MaskedImages` without problem now.

On the subject of deprecating cameraGeom, I think all "non-geometry" fields that currently exist have external `IsrCalib` representations now (crosstalk and linearity in their name-matched counterparts, gains and read noise as part of the PTC dataset), and they are available to `IsrTask` (PTC is an exception, but there's a ticket to fix that: https://jira.lsstcorp.org/browse/DM-27010).  There are some cheats still in place (notably in `obs_subaru`), where instead of using an on-disk calibration, the calibration is generated internally from the cameraGeom definition, but this is largely a case of inertia and ensuring that gen2 code still functions.

As that's all done, I'd be happy for cameraGeom to be simply the camera geometry, and ideally static (or time based like all other calibrations if the number of pre/over-scan pixels changes with camera software).  I'm unclear from the current proposal if the hierarchical structure of `cameraGeom.Camera` will remain (a `Camera` contains a set of `Detectors` each of which contains a set of `Amplifiers`).

The `AmplifierSet` classes are more complicated than I had envisioned the last time I thought about what I wanted from a "future cameraGeom".  I was thinking in terms of a `Detector` of `Amplifiers`, and then having accessors that would remove the need for bbox calculations and return masked images that could then be operated on.  A few examples I had envisioned were `geom.getSerialOverscan(Exposure, ampName)` to get the overscan region, `geom.getData(Exposure, ampName)` to get the image region (to apply the overscan, or for assembly), `geom.getDataCanonical(Exposure, ampName)` to get the image region aligned such that the readout amp was in the same corner regardless of physical orientation (for crosstalk calculations).  I had pictured that the `geom` object would be able to determine if the exposure was already assembled, and return None for fields that no longer existed (overscans/prescans).  Since the sizes are fixed, I thought this would be easier than having separate trimmed/untrimmed/assembled states.  This paragraph is mostly just a dump of what I had been thinking would be the ISR/calibs wants for the new cameraGeom.

**Comment by eacharles** [comment]
I'd like to get a sense of some of the interfaces I would be using for the EO stuff (and also to let you know about them).

The majority of the EO tasks perform a minimal ISR: overscan & bias subtraction, defect masking and possibly per-amp gain correction.    Since most of the tasks do that, I was thinking of making an EoCalibTask base class, that looks something like this:

```
 class EoCalibTaskConnections(pipeBase.PipelineTaskConnections,
                                 dimensions=("instrument", "exposure", "detector")):

    camera = cT.PrerequisiteInput(
        name="camera",
        storageClass="Camera",
        doc="Input camera to construct complete exposures.",
        dimensions=["instrument"],
        isCalibration=True,
    )
    bias = cT.PrerequisiteInput(
        name="bias",
        doc="Input bias calibration.",
        storageClass="ExposureF",
        dimensions=["instrument", "detector"],
        isCalibration=True,
    )
    defects = cT.PrerequisiteInput(
        name='defects',
        doc="Input defect tables.",
        storageClass="Defects",
        dimensions=["instrument", "detector"],
        isCalibration=True,
    )
    gains = cT.PrerequisiteInput(
        name='gains',
        doc="Input per-amp gain calibrations.",
        storageClass="AmpGains",
        dimensions=["instrument", "detector"],
        isCalibration=True,
    )
    

class EoCalibTaskConfig(pipeBase.PipelineTaskConfig,
                            pipelineConnections=EoCalibTaskConnections):

    isr = pexConfig.ConfigurableField(
        target=IsrTask,
        doc="Used to run a reduced version of ISR approrpiate for EO analyses",
    )
    


class EoCalibTask(pipeBase.PipelineTask,
                      pipeBase.CmdLineTask):

    ConfigClass = EoCalibTaskConfig    _DefaultName = "eoCalib"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.makeSubtask("isr")
    
    def run_isr_on_amp(self, ampExposure, camera, bias, defects, gains):
        det = camera.get(inputExps.dataId['detector'])
        return self.isr.run_amp_isr(ampExposure, camera, bias, defects, gains)

```

And then a class to do to a particular task might look like:


```
class BiasStabilityTaskConnections(EoCalibTaskConnections):

    inputExps = cT.Input(
        name="raw",
        doc="Build Master Bias Frames.",
        storageClass="Exposure",
        dimensions=("instrument", "exposure", "detector"),
        deferred=True, 
        multiple=True,
    )
    
    outputData = cT.Output(
        name="eo_bias_frame_stats",
        doc="Output bias frame.",
        storageClass="BiasStats",
        dimensions=("instrument", "detector"),
        isCalibration=True,
    )


class BiasStabilityTaskConfig(EoCalibTaskConfig):
    pass


class BiasStabilityTaskConfig(EoCalibTask):

    ConfigClass = BiasStabilityTaskConfig
    _DefaultName = "biasStability"

    def run(self, inputExps, camera, bias, defects, gains):
        det = camera.get(inputExps[0].dataId['detector'])
        bias_stats = BiasStats(shape=(len(det.getAmplifiers()), len(inputExps)))
        for amp in det.getAmplifiers():
            for inputExp in inputExps:
                calib_exp = self.run_isr_on_amp(inputExp.get(parameters={amp:amp}), camera, bias, defects, gains)
                self.analyze_amp_data(calib_exp, bias_stats)        
        return pipeBase.Struct(outputData=bias_stats)
  
```


Where BiasStats is a subclass of IsrCalib, and stores the per-amp, per exposure tables.

**Comment by TallJimbo** [comment]
The conversations started on this RFC have been continued on Slack and in live conversations, and I think we're in agreement that the prototype classes in this package don't have an immediate role to play.  I'm going to merge this PR just so the code isn't living on a branch and close the associated Jira ticket.  I think we may want to revive this code in the future for some of the other reasons I described in the overview document, but that's not a near-term priority.

**Pull request merged**
